apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-image-deployment
  labels:
    app: web-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-image
  template:
    metadata:
      labels:
        app: web-image
    spec:
      containers:
      - name: web-image
        image: moulisacr.azurecr.io/web-image:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-image-service
  labels:
    app: web-image
spec:
  type: LoadBalancer
  selector:
    app: web-image
  ports:
    - port: 80